version: '2'
services:
    carman_backend-app:
        image: carman_backend
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://carman_backend-mysql:3306/carman_backend?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    carman_backend-mysql:
        extends:
            file: mysql.yml
            service: carman_backend-mysql
